import "./globals.css";
import { Lato } from "next/font/google";
import localFont from "next/font/local";

const editors_note = localFont({
  src: [
    {
      path: "./fonts/EditorsNoteExtralightItalic.woff2",
      style: "italic",
    },
    {
      path: "./fonts/EditorsNote.woff2",
    },
  ],
  variable: "--font-note",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Do Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lato.variable} ${editors_note.variable}`}>
      <body>{children}</body>
    </html>
  );
}
