export const flickityOptions = {
  accessibility: true,
  adaptiveHeight: true,
  autoPlay: false,
  cellAlign: "center",
  contain: true,
  draggable: true,
  freeScroll: false,
  groupCells: false,
  initialIndex: 0,
  lazyLoad: true,
  percentPosition: true,
  prevNextButtons: false,
  pageDots: false,
  rightToLeft: false,
  setGallerySize: true,
  wrapAround: false,
  imagesLoaded: true,
};
